version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: somepass
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  script_runner:
    image: your_script_image
    depends_on:
      - postgres
    command: ["bash", "/scripts/setup.sh"]

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  transaction-service:
    build:
      context: ./services/transaction-service
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  dlq-service:
    build:
      context: ./services/dlq-service
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "3002:3002"
    depends_on:
      - postgres

volumes:
  postgres-data:
