version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  transaction-service:
    build:
      context: ./services/transaction-service
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  dlq-service:
    build:
      context: ./services/dlq-service
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - "3002:3002"
    depends_on:
      - postgres

volumes:
  postgres-data:
